language: node_js
node_js:
 - 12.18.1
cache: npm

insatll:
  - npm ci

script:
 - ng test --watch false --browsers ChromeHeadless
 - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master

