language: node_js
node_js:
 - 12.18.1
cache: npm

insatll:
  - npm ci

script:
 - npm test
 - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master

